server:
  port: 8083
spring:
  application:
    name: search-service

  jackson:
      default-property-inclusion: non_null # 配置json处理时忽略
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.30.129:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
  #--------------Feign负载均衡配置 配置全局超时时间 毫秒单位   根据业务酌情配置
ribbon:
  ConnectTimeout: 50000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 50000 #请求处理的超时时间